<h1> Checkpoint:</h1>

**Looking to see completetion and effort in completing the checkpoint. It's okay if it's not correct**

Based off this dataset with school financial, enrollment, and achievement data, we are interested in what information is a useful indicator of student performance at the state level.

This question is a bit too big for a checkpoint, however. Instead, we want you to look at smaller questions related to our overall goal. Here's the overview:

1. Choose a specific test to focus on
>Math/Reading for 4/8 grade
* Pick or create features to use
>Will all the features be useful in predicting test score? Are some more important than others? Should you standardize, bin, or scale the data?
* Explore the data as it relates to that test
>Create 2 well-labeled visualizations (graphs), each with a caption describing the graph and what it tells us about the data
* Create training and testing data
>Do you want to train on all the data? Only data from the last 10 years? Only Michigan data?
* Train a ML model to predict outcome 
>Pick if you want to do a regression or classification task. For both cases, defined _exactly_ what you want to predict, and pick any model in sklearn to use (see sklearn <a href="https://scikit-learn.org/stable/modules/linear_model.html">regressors</a> and <a href="https://scikit-learn.org/stable/auto_examples/classification/plot_classifier_comparison.html">classifiers</a>).
* Summarize your findings
>Write a 1 paragraph summary of what you did and make a recommendation about if and how student performance can be predicted

** Include comments throughout your code! Every cleanup and preprocessing task should be documented.


Of course, if you're finding this assignment interesting (and we really hope you do!), you are welcome to do more than the requirements! For example, you may want to see if expenditure affects 4th graders more than 8th graders. Maybe you want to look into the extended version of this dataset and see how factors like sex and race are involved. You can include all your work in this notebook when you turn it in -- just always make sure you explain what you did and interpret your results. Good luck!

<h2> Data Cleanup </h2>

Import numpy, pandas, matplotlib, and seaborn

(Feel free to import other libraries!)

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Load in the "states_edu.csv" dataset and take a look at the head of the data

In [5]:
df = pd.read_csv('../data/states_edu.csv')
df.head()

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
0,1992_ALABAMA,ALABAMA,1992,NaN,2678885.0,304177.0,1659028.0,715680.0,2653798.0,1481703.0,...,57948.0,58025.0,41167.0,NaN,NaN,731634.0,208.0,252.0,207.0,NaN
1,1992_ALASKA,ALASKA,1992,NaN,1049591.0,106780.0,720711.0,222100.0,972488.0,498362.0,...,9748.0,8789.0,6714.0,NaN,NaN,122487.0,NaN,NaN,NaN,NaN
2,1992_ARIZONA,ARIZONA,1992,NaN,3258079.0,297888.0,1369815.0,1590376.0,3401580.0,1435908.0,...,55433.0,49081.0,37410.0,NaN,NaN,673477.0,215.0,265.0,209.0,NaN
3,1992_ARKANSAS,ARKANSAS,1992,NaN,1711959.0,178571.0,958785.0,574603.0,1743022.0,964323.0,...,34632.0,36011.0,27651.0,NaN,NaN,441490.0,210.0,256.0,211.0,NaN
4,1992_CALIFORNIA,CALIFORNIA,1992,NaN,26260025.0,2072470.0,16546514.0,7641041.0,27138832.0,14358922.0,...,418418.0,363296.0,270675.0,NaN,NaN,5254844.0,208.0,261.0,202.0,NaN

You should always familiarize yourself with what each column in the dataframe represents. \ Read about the states_edu dataset here: https://www.kaggle.com/noriuk/us-education-datasets-unification-project

Use this space to rename columns, deal with missing data, etc. _(optional)_

<h2>Exploratory Data Analysis (EDA) </h2>

Chosen Outcome Variable for Test: **<Math/Reading for 4/8 grade>**   (Ex. Math for 8th grade)

Outcome variable chosen in Average Math Score for 4th grade




Outcome Score in the questions refers to the outcome variable you chose here.

How many different years of data are in our dataset? Use a pandas function.

In [6]:
df['YEAR'].value_counts()

2002    53
1998    53
2017    53
2015    53
2013    53
2011    53
2009    53
2007    53
2005    53
2003    53
2000    53
2019    53
1996    53
1994    53
1990    53
1992    53
1997    51
2010    51
1988    51
2016    51
1989    51
2014    51
2012    51
1991    51
2008    51
1999    51
1993    51
2006    51
2004    51
1995    51
1987    51
2001    51
1986    51
Name: YEAR, dtype: int64

Let's compare Michigan to Ohio. Which state has the higher average outcome score across all years?

In [8]:
df.STATE["Michigan"]["GRADES_4_G"].mean()
df.STATE["Ohio"]["GRADES_4_G"].mean()

KeyError: 'Ohio'

Find the average for your outcome score across all states in 2019

In [ ]:
df.YEAR["2019"]["GRADES_4_G"].mean()

Find the maximum outcome score for every state. Hint: there's a function that allows you to do this easily

In [9]:
df.groupby(["STATE", "GRADES_4_G"]).count().max(level=0)

,PRIMARY_KEY,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,SUPPORT_SERVICES_EXPENDITURE,...,GRADES_KG_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
STATE,,,,,,,,,,,,,,,,,,,,,
ALABAMA,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
ALASKA,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,1,1,1,1
ARIZONA,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
ARKANSAS,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
CALIFORNIA,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
COLORADO,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
CONNECTICUT,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
DELAWARE,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
DISTRICT_OF_COLUMBIA,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
FLORIDA,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
GEORGIA,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
HAWAII,2,2,2,2,2,2,2,2,2,2,...,2,2,2,1,1,2,1,1,1,1
IDAHO,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
ILLINOIS,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
INDIANA,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
IOWA,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
KANSAS,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,1,1,1,1
KENTUCKY,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
LOUISIANA,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
MAINE,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
MARYLAND,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
MASSACHUSETTS,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
MICHIGAN,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
MINNESOTA,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
MISSISSIPPI,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
MISSOURI,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
MONTANA,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
NEBRASKA,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
NEVADA,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
NEW_HAMPSHIRE,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
NEW_JERSEY,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
NEW_MEXICO,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
NEW_YORK,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
NORTH_CAROLINA,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,1,1,1,1
NORTH_DAKOTA,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,1,1,1,1
OHIO,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
OKLAHOMA,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
OREGON,2,2,1,1,1,1,1,1,1,1,...,2,2,2,1,1,2,1,1,1,1
PENNSYLVANIA,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
RHODE_ISLAND,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
SOUTH_CAROLINA,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
SOUTH_DAKOTA,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,1,1,1,1
TENNESSEE,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
TEXAS,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
UTAH,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
VERMONT,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
VIRGINIA,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
WASHINGTON,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
WEST_VIRGINIA,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
WISCONSIN,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
WYOMING,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

<h2> Feature Selection </h2>

After exploring the data, you now have to choose features that you would use to predict the performance of the students on a chosen test (chosen outcome variable). By the way, you can also create your own features. For example, perhaps you figured that maybe a state's expenditure per student may affect their overall academic performance so you create a expenditure_per_student feature.

Use this space to modify or create features

Final feature list: Grade 4 reading score
                    Grade 4 math score
                    Grade 8 reading score
                    Grade 8 math score
                    Total expenditure

Feature selection justification: The grade 4 and grade 8 performances are vital in determining their performance on a chosen test and the total expenditrue is important to see how much money is being put into the education

<h2>Visualization</h2>

Use any graph you wish to see the relationship of your chosen outcome variable with any features you chose

**Visualization 1**

In [ ]:
Histogram to compare grade 4 reading score and grade 4 math score across students of different sstates

**<CAPTION FOR VIZ 1>**

**Visualization 2**

In [ ]:
Scatterplot to determine average grade 4 math score based on total expenditure

**<CAPTION FOR VIZ 2>**

<h2> Data Creation </h2>

_Use this space to create train/test data_

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X = df[{'TOTAL_REVENUE', 'AVG_READING_4'}].dropna()
y = df.loc[X.index]['AVG_MATH_4']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
     X, y, test_size=??, random_state=0)

<h2> Prediction </h2>

ML Models Resource: https://medium.com/@vijaya.beeravalli/comparison-of-machine-learning-classification-models-for-credit-card-default-data-c3cf805c9a5a

Chosen ML task: **<REGRESSION

In [ ]:
# import your sklearn class here
from sklearn.linear_model import LinearRegression

In [ ]:
# create your model here
model = LinearRegression

In [ ]:
model.fit(X_train, y_train)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
# FOR CLASSIFICATION ONLY:
from sklearn.metrics import plot_confusion_matrix

plot_confusion_matrix(model, X_test, y_test,
                         cmap=plt.cm.Blues)

In [ ]:
# FOR REGRESSION ONLY: (pick a single column to visualize results)

# Results from this graph _should not_ be used as a part of your results -- it is just here to help with intuition. 
# Instead, look at the error values and individual intercepts.


col_name = 'AVG_MATH_4'
col_index = X_train.columns.get_loc(col_name)

f = plt.figure(figsize=(12,6))
plt.scatter(X_train[col_name], y_train, color = "red")
plt.scatter(X_train[col_name], model.predict(X_train), color = "green")
plt.scatter(X_test[col_name], model.predict(X_test), color = "blue")

new_x = np.linspace(X_train[col_name].min(),X_train[col_name].max(),200)
intercept = model.predict([X_train.sort_values(col_name).iloc[0]]) - X_train[col_name].min()*model.coef_[col_index]
plt.plot(new_x, intercept+new_x*model.coef_[col_index])

plt.legend(['controlled model','true training','predicted training','predicted testing'])
plt.xlabel(col_name)
plt.ylabel("Average Math Score for 4th grade students")

<h2> Summary </h2>

I wasn't able to discover findings or make an appropriate summary due to someof my functions being wrong. However, I belive my correlation of variables would be right and we could use a student's grade 4 reading score in conjunction with the variable total expenditure to determine our outcome variable which is grade 4 math score.